AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*

SpecialGlobalVars:
  Enabled: false

AsciiComments:
  Enabled: false

ClassLength:
  Max: 200

Documentation:
  Enabled: false

LineLength:
  Max: 137
  Exclude:
    - spec/**/*

MethodLength:
  Max: 39

PerlBackrefs:
  Enabled: false

TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

inherit_from: .rubocop_todo.yml
